version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: cryssantos9/nodejs-crypto-api:v1
    container_name: node-crypto-api
    restart: unless-stopped
    env_file: .env
    environment:
    - MONGO_USERNAME=$MONGO_USERNAME
    - MONGO_PASSWORD=$MONGO_PASSWORD
    - MONGO_HOSTNAME=db
    - MONGO_PORT=$MONGO_PORT
    - MONGO_DB=$MONGO_DB
    ports:
    - "3005:3005"
    volumes:
    - .:/home/node/app
    - node_modules:/home/node/app/node_modules # node modules do container sobrescreve o meu
    networks:
    - crypto-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon server.js
  db:
    image: mongo
    container_name: db-crypto-crypto-api
    restart: unless-stopped
    env_file: .env
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
    - dbdata:/data/db
    networks:
    - crypto-network


networks:
  crypto-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
